name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '50 6 * * *'

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Install libncurses
        run: sudo apt-get install -y libncurses5
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1.4
        with:
          default: true
          ldproxy: true
      - name: Build | Fmt Check
        run: cargo fmt -- --check
      - name: Build | Clippy
        run: WIFI_SSID=ssid WIFI_PASS=pass MQTT_URL=mqtt://example.org cargo clippy --features native --no-deps -- -Dwarnings
      - name: Build | Compile
        run: WIFI_SSID=ssid WIFI_PASS=pass MQTT_URL=mqtt://example.org cargo build --features native
